service: microb-challenge

provider:
  name: aws
  runtime: dotnetcore2.0
  profile: ${opt:profile, 'default'}
  timeout: 30
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DescribeTable
      Resource:
        - Fn::GetAtt: [ DynamoDBTable, Arn ]
        - Fn::Join: ["/", [ Fn::GetAtt: [DynamoDBTable, Arn], "index", "*"]]

# you can define service wide environment variables here
  environment:
    STAGE_NAME: ${self:custom.stageName}
    DYNAMO_TABLE_NAME:
      Ref: DynamoDBTable

# Custom values that can be referenced in the Cloud Formation template
custom:
  stageName: ${opt:stage, self:provider.stage}
  
  
package:
  artifact: bin/release/netcoreapp2.0/deploy-package.zip
  

functions:
  get-microb:
    handler: ServerlessApi::Microb.Read.Function::LambdaHandler
    events:
      - http:
          path: "items/{id}"
          method: "get"
  list-microb:
    handler: ServerlessApi::Microb.List.Function::LambdaHandler
    events:
      - http:
          path: "items"
          method: "get"
  create-microb:
    handler: ServerlessApi::Microb.Create.Function::LambdaHandler
    events:
      - http:
          path: "items"
          method: "post"
  delete-microb:
    handler: ServerlessApi::Microb.Delete.Function::LambdaHandler
    events:
      - http:
          path: "items/{id}"
          method: "delete"
  update-microb:
    handler: ServerlessApi::Microb.Update.Function::LambdaHandler
    events:
      - http:
          path: "items/{id}"
          method: "put"

# you can add CloudFormation resource templates here
resources:
  Parameters: ${file(infrastructure/microb-table_cfn.yml):Parameters}
  Resources:
    DynamoDBTable: ${file(infrastructure/microb-table_cfn.yml):Resources.DynamoDBTable}
